# Example qadapter for pybat
# 1. Be sure to change the <logdir> 
# 2. The nnodes, launchpad_file and fireworker_file are adjusted by the pybat qlaunch script
_fw_name: CommonAdapter
_fw_q_type: PBS
_fw_template_file: null
nnodes: null
walltime: null
launchpad_file: null
fireworker_file: null
logdir: < LOGDIR > # <----- Enter your logdir here!
rocket_launch: rapidfire --nlaunches infinite --max_loops 30 --sleep 10
