#!/bin/bash

#PBS -N pybat_$${nnodes}nodes
#PBS -q batch
#PBS -L tasks=$${nnodes}:lprocs=28
#PBS -l walltime=72:00:00
#PBS -j eo

# Set up the python environment
echo "Sourcing conda setup"
source $${conda_path}/etc/profile.d/conda.sh
echo "Loading conda environment"
conda activate $${python_env}

  # Load the modules for running VASP
  # < put the commands to load the VASP modules here >

# Go to the logdir, so any output is put here
cd $${logdir}

  # This is a workaround for making sure that fireworks with a specified number of nodes only get picked up by jobs that have that number of nodes.
echo "Adjusting fworker to number of nodes"
sed -i s/"[0-9]*nodes"/$${nnodes}nodes/ $${fireworker_file}
	
# Run the rlaunch command  <----- You shouldn't have to change this, normally. Specify rlaunch options using the rocket_launch variable in the queue adapter file.
echo "Running rlaunch command"
rlaunch -w $${fireworker_file} -l $${launchpad_file} $${rocket_launch}
